### PR TITLE
Docs site redesign and cloud separation

### PR DESCRIPTION
**Pull request by JakeSCahill**
Resolves https://github.com/redpanda-data/documentation-private/issues/2587

Preview: https://deploy-preview-68--redpanda-documentation.netlify.app/

### CODE REVIEW

**Comment by Deflaimun** [comment]
image
remove this element as it seems a leftover

**Comment by Deflaimun** [comment]
image
consider making these icons bigger. and the search icon should be monochromatic

**Comment by Deflaimun** [comment]
image
Announcement bar should be a the top of the header, as first element

**Comment by Deflaimun** [comment]
image
links for enterprise look weird. Maybe we can follow the same color scheme as the header?

**Comment by Deflaimun** [comment]
image
different paddings for these elements look weird. Either remove the right padding from the header, or add padding to the announcement

**Comment by Deflaimun** [comment]
image
on the version picker we could show the displayed version in the dropdown and show it as selected with a background color

**Comment by Deflaimun** [comment]
Animation
The announcement bar is proving to be challenging once again. I would use this opportunity to remove it completely.

**Comment by Deflaimun** [comment]
image
Don't really like the additional resources TOC, specially as it shows on every page, including the homepage. I would remove it.

**Comment by JakeSCahill** [comment]
> Are we changing the fonts? Preview shows Inter instead of Calibre

Yes 😄 We have a new design system. https://www.figma.com/design/t7IrgHK9zT8APyFIk1Y9XW/RedPanda-Design-System?node-id=95-1998&t=77W2kgxNeO2JbUEj-0

**Review by Deflaimun — APPROVED** [review]

**Pull request merged**
